"""Generate dense 12x20 DRO digit glyphs (0-9 . - + %) for ui_engine."""
from pathlib import Path

W, H = 12, 20


def blank():
    return [[0] * W for _ in range(H)]


def setp(g, x, y):
    if 0 <= x < W and 0 <= y < H:
        g[y][x] = 1


def hline(g, x0, x1, y, t=2):
    for dy in range(t):
        for x in range(x0, x1 + 1):
            setp(g, x, y + dy)


def vline(g, x, y0, y1, t=2):
    for dx in range(t):
        for y in range(y0, y1 + 1):
            setp(g, x + dx, y)


def digit(ch: str):
    g = blank()
    # padding inset
    L, R, T, B = 1, 10, 1, 18
    mid = (T + B) // 2
    if ch == "0":
        hline(g, L, R, T)
        hline(g, L, R, B - 1)
        vline(g, L, T, B)
        vline(g, R - 1, T, B)
    elif ch == "1":
        vline(g, 5, T, B, 3)
        hline(g, 3, 8, B - 1)
        setp(g, 4, T + 1)
        setp(g, 3, T + 2)
    elif ch == "2":
        hline(g, L, R, T)
        vline(g, R - 1, T, mid)
        hline(g, L, R, mid)
        vline(g, L, mid, B)
        hline(g, L, R, B - 1)
    elif ch == "3":
        hline(g, L, R, T)
        vline(g, R - 1, T, B)
        hline(g, L + 1, R, mid)
        hline(g, L, R, B - 1)
    elif ch == "4":
        vline(g, L, T, mid + 1)
        hline(g, L, R, mid)
        vline(g, R - 1, T, B)
    elif ch == "5":
        hline(g, L, R, T)
        vline(g, L, T, mid)
        hline(g, L, R, mid)
        vline(g, R - 1, mid, B)
        hline(g, L, R, B - 1)
    elif ch == "6":
        hline(g, L, R, T)
        vline(g, L, T, B)
        hline(g, L, R, mid)
        vline(g, R - 1, mid, B)
        hline(g, L, R, B - 1)
    elif ch == "7":
        hline(g, L, R, T)
        vline(g, R - 1, T, B)
    elif ch == "8":
        hline(g, L, R, T)
        hline(g, L, R, mid)
        hline(g, L, R, B - 1)
        vline(g, L, T, B)
        vline(g, R - 1, T, B)
    elif ch == "9":
        hline(g, L, R, T)
        vline(g, L, T, mid)
        hline(g, L, R, mid)
        vline(g, R - 1, T, B)
        hline(g, L, R, B - 1)
    elif ch == "-":
        hline(g, L + 1, R - 1, mid, 2)
    elif ch == ".":
        for y in range(B - 3, B + 1):
            for x in range(4, 8):
                setp(g, x, y)
    elif ch == "+":
        hline(g, L + 1, R - 1, mid, 2)
        vline(g, 5, T + 3, B - 3, 2)
    elif ch == "%":
        # compact percent
        for y in range(T, T + 4):
            for x in range(L, L + 4):
                setp(g, x, y)
        for y in range(B - 4, B):
            for x in range(R - 4, R):
                setp(g, x, y)
        for i in range(12):
            setp(g, R - 2 - i // 2, T + 2 + i)
            setp(g, R - 3 - i // 2, T + 2 + i)
    else:
        # fallback box
        hline(g, L, R, T)
        hline(g, L, R, B - 1)
        vline(g, L, T, B)
        vline(g, R - 1, T, B)
    return g


def pack_row(row):
    v = 0
    for x, bit in enumerate(row):
        if bit:
            v |= 1 << (W - 1 - x)
    return v


chars = "0123456789.-+%"
glyphs = {c: digit(c) for c in chars}

lines = [
    "//! Dense 12×20 DRO digit glyphs (host CNC readouts).",
    "//! Generated by scripts/gen_dro_digits.py — do not hand-edit bitmaps.",
    "",
    "pub const glyph_w: u8 = 12;",
    "pub const glyph_h: u8 = 20;",
    "pub const advance: i32 = 13; // glyph_w + 1px tracking",
    "",
    "/// Packed MSB-left rows. Index via glyphIndex(ch).",
    "pub const glyphs: [14][20]u16 = .{",
]
for c in chars:
    g = glyphs[c]
    rows = ", ".join(f"0x{pack_row(r):03X}" for r in g)
    lines.append(f"    // '{c}'")
    lines.append(f"    .{{ {rows} }},")
lines += [
    "};",
    "",
    "pub fn glyphIndex(ch: u8) ?usize {",
    "    return switch (ch) {",
]
for i, c in enumerate(chars):
    if c == "'":
        lit = r"'\''"
    elif c == "\\":
        lit = r"'\\'"
    else:
        lit = f"'{c}'"
    lines.append(f"        {lit} => {i},")
lines += [
    "        else => null,",
    "    };",
    "}",
    "",
]

out = Path("src/modulus/ui_engine/font_digits.zig")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("wrote", out)
