#!/usr/bin/env python3
"""Apply M3 sentence-case UX string replacements to Tab5 UI C sources."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "firmware" / "tab5" / "components" / "modulus_zig"

# Longest-first applied below.
PAIRS: list[tuple[str, str]] = [
    ('"CYCLE START"', '"Cycle start"'),
    ('"STOP CYCLE"', '"Stop cycle"'),
    ('"FEED HOLD"', '"Feed hold"'),
    ('"FEED RESUME"', '"Feed resume"'),
    ('"HOME ALL"', '"Home all"'),
    ('"CLEAR ALARM"', '"Clear alarm"'),
    ('"SOFT RESET"', '"Soft reset"'),
    ('"DOOR OPEN"', '"Door open"'),
    ('"FEED OVERRIDE"', '"Feed override"'),
    ('"SPINDLE OVERRIDE"', '"Spindle override"'),
    ('"JOG MODE & INCREMENT"', '"Jog mode & increment"'),
    ('"HOMING"', '"Homing..."'),
    ('"MACHINE CONTROL"', '"Machine control"'),
    ('"DEVICE POWER"', '"Device power"'),
    ('"Power Menu"', '"Power menu"'),
    ('"Shutdown Device"', '"Shut down device"'),
    ('"Restart Device"', '"Restart device"'),
    ('"Clear Alarm"', '"Clear alarm"'),
    ('"Power Off"', '"Power off"'),
    ('"System Settings"', '"System settings"'),
    ('"Machine Name"', '"Machine name"'),
    ('"Rename Profile"', '"Rename profile"'),
    ('"Connection Profiles"', '"Connection profiles"'),
    ('"Controller Settings ($$)"', '"Controller settings ($$)"'),
    ('"WCS Lock & Names"', '"WCS lock & names"'),
    ('"Idle Lock"', '"Idle lock"'),
    ('"Maintenance Meters"', '"Maintenance meters"'),
    ('"Edit Jog Increments"', '"Edit jog increments"'),
    ('"Edit Quick Button"', '"Edit quick button"'),
    ('"Add Quick Button"', '"Add quick button"'),
    ('"MPG Direction"', '"MPG direction"'),
    ('"Arrange Quick Buttons"', '"Arrange quick buttons"'),
    ('"Feed Hold"', '"Feed hold"'),
    ('"Set as Active & Connect"', '"Set as active & connect"'),
    ('"Scan to find..."', '"Scan to find"'),
    ('"Reset Display & Theme"', '"Reset display & theme"'),
    ('"Reset Machine Settings"', '"Reset machine settings"'),
    ('"Reset Power Settings"', '"Reset power settings"'),
    ('"Reset CNC Connection"', '"Reset CNC connection"'),
    ('"Open Wireless ESP-NOW"', '"Open wireless ESP-NOW"'),
    ('"Reset Dashboard & Handwheel"', '"Reset dashboard & handwheel"'),
    ('"Reset Network Defaults"', '"Reset network defaults"'),
    ('"Scan for Devices"', '"Scan for devices"'),
    ('"Power & Sleep"', '"Power & sleep"'),
    ('"CNC Connection"', '"CNC connection"'),
    ('"Dashboard & Handwheel"', '"Dashboard & handwheel"'),
    ('"Time Zone"', '"Time zone"'),
    ('"Time Format"', '"Time format"'),
    ('"Open Configure"', '"Open configure"'),
    ('"MPG REM"', '"MPG rem"'),
    ('"MPG OFF"', '"MPG off"'),
    ('"OFFLINE"', '"Offline"'),
    ('"MOTION CONTROL SYSTEMS"', '"Motion control systems"'),
    ('"CONNECTION PROFILES"', '"Connection profiles"'),
    ('"TRANSPORT PARAMETERS"', '"Transport parameters"'),
    ('"WORK COORDINATE SYSTEM"', '"Work coordinate system"'),
    ('"LOGGING & DIAGNOSTICS"', '"Logging & diagnostics"'),
    ('"GRBL / GRBLHAL REFERENCE"', '"Grbl / GrblHAL reference"'),
    ('"HANDWHEEL REFERENCE"', '"Handwheel reference"'),
    ('"STORAGE REFERENCE"', '"Storage reference"'),
    ('"YOUR CUSTOM BUTTONS"', '"Your custom buttons"'),
    ('"PENDANT SOFT LIMITS"', '"Pendant soft limits"'),
    ('"WIRELESS PROTOCOLS"', '"Wireless protocols"'),
    ('"802.15.4 RADIOS"', '"802.15.4 radios"'),
    ('"CONNECTION STATUS"', '"Connection status"'),
    ('"RELATED SETTINGS"', '"Related settings"'),
    ('"PLANNED FEATURES"', '"Planned features"'),
    ('"ACTIVE TRANSPORT"', '"Active transport"'),
    ('"LANGUAGE & REGION"', '"Language & region"'),
    ('"FIRMWARE UPDATE"', '"Firmware update"'),
    ('"SYSTEM ACTIONS"', '"System actions"'),
    ('"BATTERY BEHAVIOR"', '"Battery behavior"'),
    ('"BATTERY STATUS"', '"Battery status"'),
    ('"DISPLAY SLEEP"', '"Display sleep"'),
    ('"SYSTEM SLEEP"', '"System sleep"'),
    ('"POWER RAILS"', '"Power rails"'),
    ('"SESSION POLICY"', '"Session policy"'),
    ('"MACHINE IDENTITY"', '"Machine identity"'),
    ('"CONTROLLER SYNC"', '"Controller sync"'),
    ('"WORK ENVELOPE"', '"Work envelope"'),
    ('"SETTINGS BACKUP"', '"Settings backup"'),
    ('"MICROSD CARD"', '"microSD card"'),
    ('"TOUCH FEEDBACK"', '"Touch feedback"'),
    ('"SYSTEM SOUNDS"', '"System sounds"'),
    ('"JOG INCREMENTS"', '"Jog increments"'),
    ('"QUICK BUTTONS"', '"Quick buttons"'),
    ('"CONFIRM POLICY"', '"Confirm policy"'),
    ('"JOG COALESCE"', '"Jog coalesce"'),
    ('"HANDWHEEL / MPG"', '"Handwheel / MPG"'),
    ('"MPG DIRECTION"', '"MPG direction"'),
    ('"ACTIVE AXES"', '"Active axes"'),
    ('"DASHBOARD SLOTS"', '"Dashboard slots"'),
    ('"LAYOUT PREVIEW"', '"Layout preview"'),
    ('"CUSTOM NAMES"', '"Custom names"'),
    ('"PAIRED DEVICES"', '"Paired devices"'),
    ('"SAVED DEVICES"', '"Saved devices"'),
    ('"NETWORK CONTROL"', '"Network control"'),
    ('"DEBUG STATE"', '"Debug state"'),
    ('"SAVED PEERS"', '"Saved peers"'),
    ('"IP CONFIG"', '"IP config"'),
    ('"ESP-NOW PEER"', '"ESP-NOW peer"'),
    ('"ESP-NOW DEBUG"', '"ESP-NOW debug"'),
    ('"MASSO LINK"', '"Masso Link"'),
    ('"DATE & TIME"', '"Date & time"'),
    ('"DEVICE LOCK"', '"Device lock"'),
    ('"AUTO LOCK"', '"Auto lock"'),
    ('"IDLE LOCK"', '"Idle lock"'),
    ('"USB HOST"', '"USB host"'),
    ('"BRIGHTNESS"', '"Brightness"'),
    ('"PERFORMANCE"', '"Performance"'),
    ('"ORIENTATION"', '"Orientation"'),
    ('"MICROPHONE"', '"Microphone"'),
    ('"MAINTENANCE"', '"Maintenance"'),
    ('"PARAMETERS"', '"Parameters"'),
    ('"TROUBLESHOOTING"', '"Troubleshooting"'),
    ('"DISCOVERED"', '"Discovered"'),
    ('"DISCOVERY"', '"Discovery"'),
    ('"NETWORKS"', '"Networks"'),
    ('"ANTENNA"', '"Antenna"'),
    ('"SECURITY"', '"Security"'),
    ('"ADVANCED"', '"Advanced"'),
    ('"ACTIONS"', '"Actions"'),
    ('"SPINDLE"', '"Spindle"'),
    ('"RESULTS"', '"Results"'),
    ('"TRAFFIC"', '"Traffic"'),
    ('"STATUS"', '"Status"'),
    ('"MEMORY"', '"Memory"'),
    ('"HEALTH"', '"Health"'),
    ('"DEVICE"', '"Device"'),
    ('"RUNTIME"', '"Runtime"'),
    ('"VOLUME"', '"Volume"'),
    ('"THEME"', '"Theme"'),
    ('"TOUCH"', '"Touch"'),
    ('"MOTION"', '"Motion"'),
    ('"PROBE"', '"Probe"'),
    ('"UNITS"', '"Units"'),
    ('"LOCKS"', '"Locks"'),
    ('"TRAVEL"', '"Travel"'),
    ('"RADIO"', '"Radio"'),
    ('"PEERS"', '"Peers"'),
    ('"POWER"', '"Power"'),
    ('"DEBUG"', '"Debug"'),
    ('"SAVED"', '"Saved"'),
    ('"TIME"', '"Time"'),
    ('"CUSTOM"', '"Custom"'),
    ('"COOLANT"', '"Coolant"'),
    ('"MACRO"', '"Macro"'),
    ('"MIST"', '"Mist"'),
    ('"STEP"', '"Step"'),
    ('"CONT"', '"Cont"'),
    ('"VELO"', '"Velo"'),
    ('"HOME"', '"Home"'),
    ('"ZERO"', '"Zero"'),
    ('"RESET"', '"Reset"'),
    ('"HOLD"', '"Hold"'),
    ('"IDLE"', '"Idle"'),
    ('"ALARM"', '"Alarm"'),
    ('"DOOR"', '"Door"'),
    ('"CHECK"', '"Check"'),
    ('"SLEEP"', '"Sleep"'),
    ('"TOOL"', '"Tool"'),
    ('"FEED"', '"Feed"'),
    ('"ACTIVE"', '"Active"'),
    ('"CNC &\\nConnection"', '"CNC &\\nconnection"'),
    ('"Dashboard &\\nHandwheel"', '"Dashboard &\\nhandwheel"'),
    ('"Display &\\nTheme"', '"Display &\\ntheme"'),
    ('"Audio &\\nHaptics"', '"Audio &\\nhaptics"'),
    ('"Storage &\\nDiagnostics"', '"Storage &\\ndiagnostics"'),
    ('"System &\\nAbout"', '"System &\\nabout"'),
    ('"Wi-Fi Advanced"', '"Wi-Fi advanced"'),
    ('"Bluetooth Advanced"', '"Bluetooth advanced"'),
    ('"Zigbee Advanced"', '"Zigbee advanced"'),
    ('"Thread Advanced"', '"Thread advanced"'),
    ('"ESP-NOW Advanced"', '"ESP-NOW advanced"'),
    ('"Eject SD Card"', '"Eject SD card"'),
    ('"Date:"', '"Date"'),
    ('"Time:"', '"Time"'),
]


def main() -> None:
    pairs = sorted(PAIRS, key=lambda p: len(p[0]), reverse=True)
    changed: list[str] = []
    for path in sorted(ROOT.glob("ui_*.c")):
        text = path.read_text(encoding="utf-8")
        orig = text
        for old, new in pairs:
            text = text.replace(old, new)
        if text != orig:
            # Preserve existing newlines (CRLF vs LF).
            path.write_bytes(text.encode("utf-8"))
            changed.append(path.name)
    print(f"Changed {len(changed)} files")
    for name in changed:
        print(name)


if __name__ == "__main__":
    main()
