#!/usr/bin/env python3
"""Generate zb_devdb_data.c from zigbee-herdsman-converters (zigbee2mqtt dataset).

Usage:  python tools/gen_zb_devdb.py firmware/tab5/components/modulus_zig/zb_devdb_data.c
Downloads the upstream repo (master zip), parses src/devices/*.ts device
definitions, and emits a sorted C table keyed by over-the-air zigbeeModel.
Run on a PC with internet; rebuild the P4 firmware afterwards.
"""
import io
import re
import sys
import urllib.request
import zipfile

ZIP_URL = "https://codeload.github.com/Koenkk/zigbee-herdsman-converters/zip/refs/heads/master"
MAX_S = {"zm": 32, "vendor": 24, "model": 24, "desc": 56}

def c_escape(s: str, cap: int) -> str:
    s = s[:cap]
    return s.replace("\\", "\\\\").replace('"', '\\"')

def parse_ts(text: str):
    """Yield (zigbee_model, vendor, model, description) from one devices/*.ts."""
    for m in re.finditer(
        r"zigbeeModel:\s*\[(?P<zm>[^\]]*)\]"
        r"(?P<body>.*?)"
        r"(?=zigbeeModel:\s*\[|\Z)",
        text,
        re.S,
    ):
        body = m.group("body")
        def field(name):
            fm = re.search(name + r":\s*(['\"])(?P<v>(?:\\.|(?!\1).)*)\1", body)
            return fm.group("v").replace("\\'", "'").replace('\\"', '"') if fm else ""
        vendor, model, desc = field("vendor"), field("model"), field("description")
        if not model:
            continue
        for zm_m in re.finditer(r"(['\"])(?P<v>(?:\\.|(?!\1).)*)\1", m.group("zm")):
            zm = zm_m.group("v").replace("\\'", "'").rstrip()
            if zm:
                yield zm, vendor, model, desc

def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "zb_devdb_data.c"
    print("downloading", ZIP_URL)
    data = urllib.request.urlopen(ZIP_URL, timeout=120).read()
    zf = zipfile.ZipFile(io.BytesIO(data))
    entries = {}
    n_files = 0
    for name in zf.namelist():
        if "/src/devices/" in name and name.endswith(".ts") and "index" not in name:
            n_files += 1
            for zm, vendor, model, desc in parse_ts(zf.read(name).decode("utf-8", "replace")):
                entries.setdefault(zm, (vendor, model, desc))  # first wins
    table = sorted(entries.items())
    print(f"parsed {n_files} files -> {len(table)} zigbeeModel entries")
    if len(table) < 1000:
        sys.exit("ERROR: suspiciously few entries - upstream layout changed?")

    with open(out_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("/* GENERATED by tools/gen_zb_devdb.py - do not edit.\n")
        f.write(f" * Source: zigbee-herdsman-converters master ({len(table)} entries).\n")
        f.write(" * Sorted by zigbee_model for zb_devdb_find() binary search. */\n")
        f.write('#include "zb_devdb.h"\n\n')
        f.write("const zb_devdb_entry_t zb_devdb_table[] = {\n")
        for zm, (vendor, model, desc) in table:
            f.write('    {"%s", "%s", "%s", "%s"},\n' % (
                c_escape(zm, MAX_S["zm"]), c_escape(vendor, MAX_S["vendor"]),
                c_escape(model, MAX_S["model"]), c_escape(desc, MAX_S["desc"])))
        f.write("};\n")
        f.write(f"const unsigned zb_devdb_count = {len(table)}u;\n")
    print("wrote", out_path)

if __name__ == "__main__":
    main()
